name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install vcpkg (Windows)
      if: runner.os == 'Windows'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install sdl2:x64-windows

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Configure CMake (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mega-emu-${{ runner.os }}
        path: |
          build/Release/mega_emu*
          build/mega_emu*
