name: Spell Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install cspell
      run: npm install -g cspell

    - name: Check Spelling
      run: cspell "**/*.{md,c,h,cpp,hpp,lua}" --config .github/workflows/cspell.json

    - name: Check Documentation Spelling
      run: cspell "docs/**/*.{md,txt}" --config .github/workflows/cspell.json
